### ISSUE TITLE
BUG: key error 

### ISSUE THREAD

**Issue by RuiFilipeCampos** [RuiFilipeCampos/MontyCarlo#21]
```
seeding with: 0, 0, 0, 123
seeding with: 0, 0, 0, 89715
Traceback (most recent call last):
D:\a\MontyCarlo\MontyCarlo\tests\_cmd.py
  File "D:\a\MontyCarlo\MontyCarlo\MontyCarlo\materials\database.py", line 553, in __getitem__
['import_test.py', '--built_inplace']
The path 'D:\a\MontyCarlo\MontyCarlo' has been appended to `sys.path`. If the path looks weird, you probably ran the script as a python file. Please run it as a module:
`python -m unit_test --built_inplace`
Importing MontyCarlo
Importing .settings
_________________________________________________________________
INSTALL PATH:  D:\a\MontyCarlo\MontyCarlo\MontyCarlo
----
DEBUG: False
---------------
PHOTON CUT OFF: 5110.0 MeV
----
ELECTRON CUT OFF: 100000.0 MeV
---------------------------------------------


BRANCH: pre-alpha/0.0.41

____INIT_____
Importing `.plotter`
Importing .tools.interpol1
Importing .tools.CubicInverseTransform ...
Importing `.materials.pyRelax`
Importing .materials.database
Importing .tools.vectors
Importing .tools.RITA
>>>> IMPORTING material.photon.CrossSection.pyx
>>>> IMPORTING material.photon.pyx
Importing `.materials.materials`
Importing `.materials.logger`
>>>> IMPORTING main.pyx
Importing .materials.electron.main
Importing `.types`
Importing .particles.particle
Importing .geometry.main
Importing .geometry.CSG
Importing .particles.positrons
Importing particles.photons
Importing .particles.electrons
Size of mater 128
Importing .sources
SEED: 725832839
Creating a material
Compiling data for material 'Untitled'
0
NUMBER OF PROFILES 1
1 1
0
1
2
NUMBER OF PROFILES 3
8 4
        DATA PROCESSING IN PYTHON
        > a = 2.9395944556963114
                err =  0.0 %
    2x<Atom Z=1, Aw = 1.00797 amu, I = 19.2 eV> 
    <Shell #1, fk = 1.0, Uk = 13.6 eV, Wk = 40.360955827712104 eV> 
 
    1x<Atom Z=8, Aw = 15.9994 amu, I = 95.0 eV> 
    <Shell #1, fk = 2.0, Uk = 538.0 eV, Wk = 1581.521246377744 eV> 
    <Shell #3, fk = 3.33, Uk = 21.049999999999997 eV, Wk = 62.8342736655728 eV> 
 

        GENERATING GOS MODEL IN CYTHON
        > creating shells
        > making density corrections
        > note: KE = logspace(1, 9, 5_000)
        GENERATING FULL SP
    return self.__cache__[Z+1]
KeyError: 8.0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\MontyCarlo\MontyCarlo\tests\import_test.py", line 14, in <module>
    myco.Mat({1:2, 8:1}, 1)
  File "MontyCarlo\materials\materials.pyx", line 894, in MontyCarlo.materials.materials.Mat
  File "MontyCarlo\materials\materials.pyx", line 990, in MontyCarlo.materials.materials.Material.__init__
  File "MontyCarlo\materials\electron\main.pyx", line 295, in MontyCarlo.materials.electron.main.Electron.__init__
  File "MontyCarlo\materials\electron\main.pyx", line 614, in MontyCarlo.materials.electron.main.Inelastic.__init__
  File "MontyCarlo\materials\electron\GOSfinal.pyx", line 127, in MontyCarlo.materials.electron.GOSfinal.gosMolecule.__init__
  File "MontyCarlo\materials\electron\GOSfinal.pyx", line 368, in MontyCarlo.materials.electron.GOSfinal.gosAtom.__init__
  File "MontyCarlo\materials\electron\GOSfinal.pyx", line 1088, in MontyCarlo.materials.electron.GOSfinal.gosInnerShell.__init__
  File "D:\a\MontyCarlo\MontyCarlo\MontyCarlo\materials\database.py", line 555, in __getitem__
    self.__cache__[Z+1] = getEEDL(Z+1)
  File "D:\a\MontyCarlo\MontyCarlo\MontyCarlo\materials\database.py", line 294, in getEEDL
    EEDL_dict = get_bookmarked_text(EEDL_path)
NameError: name 'EEDL_path' is not defined
Error: Process completed with exit code 1.
```

**Comment by RuiFilipeCampos** [comment]
https://github.com/RuiFilipeCampos/MontyCarlo/tree/fix/%2321

**Comment by RuiFilipeCampos** [comment]
https://github.com/RuiFilipeCampos/MontyCarlo/blob/b855154b18e412a559a5fd812f111f7d32edc0f0/MontyCarlo/materials/electron/main.pyx#L608-L628

**Comment by RuiFilipeCampos** [comment]
https://github.com/RuiFilipeCampos/MontyCarlo/blob/b855154b18e412a559a5fd812f111f7d32edc0f0/MontyCarlo/materials/electron/main.pyx#L614

**Comment by RuiFilipeCampos** [comment]
https://github.com/RuiFilipeCampos/MontyCarlo/blob/b855154b18e412a559a5fd812f111f7d32edc0f0/MontyCarlo/materials/electron/GOSfinal.pyx#L86-L292

**Comment by RuiFilipeCampos** [comment]
https://github.com/RuiFilipeCampos/MontyCarlo/blob/d6feeb50de3d49a41f7e168f296c5ddb101d64a6/MontyCarlo/materials/database.py#L280-L300
