### ISSUE TITLE
Does not find elastic db

### ISSUE THREAD

**Issue by RuiFilipeCampos** [RuiFilipeCampos/MontyCarlo#23]
```
       MAKING ELASTIC SAMPLER
Traceback (most recent call last):
  File "import_test.py", line 14, in <module>
    myco.Mat({1:2, 8:1}, 1)
  File "MontyCarlo\materials\materials.pyx", line 894, in MontyCarlo.materials.materials.Mat
  File "MontyCarlo\materials\materials.pyx", line 990, in MontyCarlo.materials.materials.Material.__init__
  File "MontyCarlo\materials\electron\main.pyx", line 321, in MontyCarlo.materials.electron.main.Electron.__init__
  File "MontyCarlo\materials\electron\main.pyx", line 1066, in MontyCarlo.materials.electron.main.Elastic.__init__
  File "MontyCarlo\materials\electron\main.pyx", line 1363, in MontyCarlo.materials.electron.main.Elastic.compose
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\numpy\lib\npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\a\\MontyCarlo\\MontyCarlo\\MontyCarlo\\materials\\electron\\elastic/1/HEtransportTCS.npy'

```

**Comment by RuiFilipeCampos** [comment]
This has been fixed.
