### ISSUE TITLE
testing the cmd

### ISSUE THREAD

**Issue by RuiFilipeCampos** [RuiFilipeCampos/MontyCarlo#33]
```
myco@C:\Users\Rui Campos\.conda\envs\py361\Scripts>cd ..
myco@C:\Users\Rui Campos\.conda\envs\py361>cd ..
myco@C:\Users\Rui Campos\.conda\envs>cd ..
myco@C:\Users\Rui Campos\.conda>cd ..
myco@C:\Users\Rui Campos>cd Projects
myco@C:\Users\Rui Campos\Projects>ls
# Sorted alphabetically with capital letters coming first.

DIRECTORIES:
    (...)

FILES:
     autosetup.py
     setup.py
     teste.py

myco@C:\Users\Rui Campos\Projects>create onion
The name of your project is: onion


myco@C:\Users\Rui Campos\Projects>open onion
Initing MontyCarlo, just a sec....
Your project is now open!

myco@onion>build
myco@onion>run
```

```
C:\Users\Rui Campos\Downloads
Traceback (most recent call last):
  File "c:\users\rui campos\.conda\envs\py361\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\rui campos\.conda\envs\py361\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Rui Campos\.conda\envs\py361\Scripts\myco.exe\__main__.py", line 7, in <module>
  File "c:\users\rui campos\.conda\envs\py361\lib\site-packages\MontyCarlo\cl\myco.py", line 266, in main
    MontyCarloShell().cmdloop()
  File "c:\users\rui campos\.conda\envs\py361\lib\cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "c:\users\rui campos\.conda\envs\py361\lib\cmd.py", line 217, in onecmd
    return func(arg)
  File "c:\users\rui campos\.conda\envs\py361\lib\site-packages\MontyCarlo\cl\myco.py", line 169, in do_open
    MontyCarloProjectShell().cmdloop(project_path)
  File "c:\users\rui campos\.conda\envs\py361\lib\site-packages\MontyCarlo\cl\myco.py", line 245, in cmdloop
    super(MontyCarloProjectShell, self).cmdloop()
  File "c:\users\rui campos\.conda\envs\py361\lib\cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "c:\users\rui campos\.conda\envs\py361\lib\cmd.py", line 217, in onecmd
    return func(arg)
  File "c:\users\rui campos\.conda\envs\py361\lib\site-packages\MontyCarlo\cl\myco.py", line 252, in do_run
    os.chdir(root.name)
FileNotFoundError: [WinError 2] O sistema não conseguiu localizar o ficheiro especificado: 'onion'

```

- [ ] termcolor not in requirements

**Comment by RuiFilipeCampos** [comment]
https://github.com/RuiFilipeCampos/MontyCarlo/blob/76ff2bf539d5863a0141f31151722c663f9abc9d/MontyCarlo/cl/myco.py#L247-L262

**Comment by RuiFilipeCampos** [comment]
```Python
def do_run(self, args): 
     import os 
     root = MontyCarloProjectShell.path 
     old_dir = os.getcwd()
     os.chdir(str(root)) # <---- will complain of spaces, for sure
  

     print(colored(
           "python main.py", "red"
    )) 

     os.system("python main.py") # <-- needs proper error handling
  
     os.chdir(old_dir) 


```

**Comment by RuiFilipeCampos** [comment]
> 
> 
> ```python
> def do_run(self, args): 
>      import os 
>      root = MontyCarloProjectShell.path 
>      old_dir = os.getcwd()
>      os.chdir(str(root)) # <---- will complain of spaces, for sure
>   
> 
>      print(colored(
>            "python main.py", "red"
>     )) 
> 
>      os.system("python main.py") # <-- needs proper error handling
>   
>      os.chdir(old_dir) 
> ```

worked

**Comment by RuiFilipeCampos** [comment]
however, this wheel is not able to run the build

works by directly running it with the current version

I did not touch anything, must be the cl somehow

**Comment by RuiFilipeCampos** [comment]
https://github.com/RuiFilipeCampos/MontyCarlo/blob/af2ba6444c47c15a74cd4a6bc4b5e0a15464f73d/MontyCarlo/particles/electrons.pyx#L922-L1164

**Comment by RuiFilipeCampos** [comment]
> 
> 
> > however, this wheel is not able to run the build
> > works by directly running it with the current version
> > I did not touch anything, must be the cl somehow
> 
> got it I think
> 
> https://github.com/RuiFilipeCampos/MontyCarlo/blob/af2ba6444c47c15a74cd4a6bc4b5e0a15464f73d/MontyCarlo/particles/positrons.pyx#L570-L1015

very likely this thing

https://github.com/RuiFilipeCampos/MontyCarlo/blob/af2ba6444c47c15a74cd4a6bc4b5e0a15464f73d/MontyCarlo/particles/positrons.pyx#L661-L663

**Comment by RuiFilipeCampos** [comment]
https://github.com/RuiFilipeCampos/MontyCarlo/blob/af2ba6444c47c15a74cd4a6bc4b5e0a15464f73d/MontyCarlo/particles/positrons.pyx#L254

ofc they don't die, their not losing energy

**Comment by RuiFilipeCampos** [comment]
> 
> 
> https://github.com/RuiFilipeCampos/MontyCarlo/blob/9b1b9e37549cdf2fd23efc66f0accfcd2c04da34/setup_amd64.py#L85

needs '_random' for linking to occur. I've deleted '_random' a long time ago

**Comment by RuiFilipeCampos** [comment]
The command-line will be developed in the context of the docker container.
