### ISSUE TITLE
(macos) import MontyCarlo fails

### ISSUE THREAD

**Issue by RuiFilipeCampos** [RuiFilipeCampos/MontyCarlo#5]
**Describe the bug**
Traceback (most recent call last):

```
  File "<string>", line 1, in <module>
  File "/Users/runner/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/MontyCarlo/__init__.py", line 21, in <module>
    from ._init import eax
  File "MontyCarlo/_init.pyx", line 79, in init MontyCarlo._init
ValueError: Buffer dtype mismatch, expected 'int' but got 'long'
```

**To Reproduce**
Do first import on macos.

**Desktop (please complete the following information):**
 - OS: macos-latest

**Comment by RuiFilipeCampos** [comment]
https://github.com/RuiFilipeCampos/MontyCarlo/blob/22e3799146b5cdac1d97d44084f69b7d503e7c1b/MontyCarlo/_init.pyx#L79

**Comment by RuiFilipeCampos** [comment]
Solved it!
