### ISSUE TITLE
Interesting Repo!

### ISSUE THREAD

**Issue by VallesMarinerisExplorer** [RuiFilipeCampos/MontyCarlo#64]
Hi there! Cool repo!

I have been trying to run one of the examples and I think there is an issue with reading data.pkl? I am not sure though. Any thoughts on this? Thanks for your help!

Traceback (most recent call last):
  File "C:/MontyCarloParticleTest.py", line 9, in <module>
    water = Mat({1: 2, 8: 1}, 1, name="Water")
  File "MontyCarlo\materials\materials.pyx", line 894, in MontyCarlo.materials.materials.Mat
  File "MontyCarlo\materials\materials.pyx", line 998, in MontyCarlo.materials.materials.Material.__init__
FileNotFoundError: [Errno 2] No such file or directory: 'mat/Water_C10.1_C20.1_Wcc100000.0_Wcr10000.0'

**Comment by RuiFilipeCampos** [comment]
Thanks ! I'm super excited to be responding to my first issue !!

In order to run your script, you need to set up the folder structure like so:

```
├── /mat
├── /geo
├── /out
└── MontyCarloParticleTest.py
```

The reason why it doesn't create those empty folders automatically (mat, geo and out) is that I was meaning to make a command line interface that prepares all this automatically. But in hindsight, it makes more sense to have the folders being created if they're not there, so I think I'll just open PR for it !
