### ISSUE TITLE
Doesn't find database.

### ISSUE THREAD

**Issue by RuiFilipeCampos** [RuiFilipeCampos/MontyCarlo#9]
**Describe the bug**
```seeding with: 0, 0, 0, 123
Traceback (most recent call last):
Importing .settings
  File "<string>", line 1, in <module>
_________________________________________________________________
  File "/Users/runner/work/MontyCarlo/MontyCarlo/MontyCarlo/__init__.py", line 29, in <module>
INSTALL PATH:  /Users/runner/work/MontyCarlo/MontyCarlo/MontyCarlo
    from MontyCarlo.geometry.main import *
----
  File "MontyCarlo/geometry/main.pyx", line 1, in init MontyCarlo.geometry.main
DEBUG: False
    # distutils: language = c++
---------------
  File "MontyCarlo/materials/pyRelax.pyx", line 56, in init MontyCarlo.materials.pyRelax
PHOTON CUT OFF: 5110.0 MeV
    from . import database as db
----
  File "/Users/runner/work/MontyCarlo/MontyCarlo/MontyCarlo/materials/database.py", line 596, in <module>
ELECTRON CUT OFF: 100000.0 MeV
    EADL = [getEADL(Z) for Z in range(1, 101)]
---------------------------------------------
  File "/Users/runner/work/MontyCarlo/MontyCarlo/MontyCarlo/materials/database.py", line 596, in <listcomp>

    EADL = [getEADL(Z) for Z in range(1, 101)]

  File "/Users/runner/work/MontyCarlo/MontyCarlo/MontyCarlo/materials/database.py", line 222, in getEADL
BRANCH: pre-alpha/0.0.41
    Aw, EADL_dict = get_bookmarked_text_EADL(EADL_path)

  File "/Users/runner/work/MontyCarlo/MontyCarlo/MontyCarlo/materials/database.py", line 158, in get_bookmarked_text_EADL
Importing .install
    with open(path, "r") as file:

FileNotFoundError: [Errno 2] No such file or directory: '/Users/runner/work/MontyCarlo/MontyCarlo/MontyCarlo/materials\\EADL\\1.txt'
The data being download can be seen in `https://github.com/RuiFilipeCampos/MontyCarlo/tree/pre-alpha/0.0.41/docs` 
in the `EADL`, `EPDL`, `EEDL`, and `elastic` folders. 

Downloading EADL...
Done!

Downloading EPDL...
Done!

Downloading EEDL...
Done!

Downloading electron elastic data...
Done!

Downloading electron positron data...
Done!

____INIT_____
Importing .plotter
Importing .tools.interpol1
Importing .tools.CubicInverseTransform ...
Importing .materials.pyRelax
Importing .materials.database

    ________________
    > Reading EADL. 
Error: Process completed with exit code 1.```

**To Reproduce**
Run build_and_run.yml

**Comment by RuiFilipeCampos** [comment]
`FileNotFoundError: [Errno 2] No such file or directory: '/Users/runner/work/MontyCarlo/MontyCarlo/MontyCarlo/materials\\EADL\\1.txt'`

**Comment by RuiFilipeCampos** [comment]
https://github.com/RuiFilipeCampos/MontyCarlo/blob/22e3799146b5cdac1d97d44084f69b7d503e7c1b/MontyCarlo/materials/database.py#L220
